[build]
  command = "npm install && npx tailwindcss -i src/input.css -o css/style.css --minify"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
